### ISSUE TITLE
Enable sorting by Artist / full GD3 adoption

### ISSUE THREAD

**Issue by now-its-dark** [a-busman/SquareWaveSwift#3]
Since VGMs typically include the composer in their GD3 tag, it should be totally achievable to use this as sorting criteria. It elevates the artistry of the medium to surface this data and is going to be of interest to most listeners.
https://www.smspower.org/uploads/Music/gd3spec100.txt

**Comment by a-busman** [comment]
This should be added in v1.2.3, currently submitted for review.

Commit: 453a417c4a106834d4d6500e9988f5b8d3d6cdea
