### ISSUE TITLE
List alphabet letters overlap with buttons / spacing adjustment needed for iPad Pro 11"

### ISSUE THREAD

**Issue by now-its-dark** [a-busman/SquareWaveSwift#4]
This was screen-capped from an iPad Pro 11", can't speak to other models, but it appears the spacing is off for the ipad version in the tracklist on this device.

![IMG_0068](https://user-images.githubusercontent.com/5728860/89376756-57d8df00-d6a5-11ea-8764-d0b49142dd0c.jpg)

**Comment by a-busman** [comment]
Should be fixed in 1.2.4. dd102ed7ed8d452c4189ab5729e7b52dd0978e81

Submitted for review.
